apiVersion: v1
kind: Namespace
metadata:
  name: secure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auditor
  namespace: secure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secure
  name: auditor-view
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auditor-binding
  namespace: secure
subjects:
- kind: ServiceAccount
  name: auditor
  namespace: secure
roleRef:
  kind: Role
  name: auditor-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: unpriv-pod
  namespace: secure
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: nginxinc/nginx-unprivileged:alpine
    ports:
    - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: secure
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
